repos:
  - repo: local
    hooks:
      - id: validate-branch-name
        name: Validate Branch Name
        entry: python custom-hook-validation/branch-name-validation.py
        language: python
        stages: [pre-commit, pre-push]
