name: Deploy Stack
on:
  workflow_dispatch:
  push:
    branches:
      - prepare/iac-video07

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          template: ${{ env.TEMPLATE_FILE }}
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: UserPassword=${{ secrets.USER_PASSWORD }}
          no-fail-on-empty-changeset: "1"
