name: Basic Create Stack

on:
  push:
    branches:
      - prepare/iac-video08
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      STACK_NAME: stack-created-with-github-actions
      TEMPLATE_FILE: templates/basic/first-template.yaml

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Create or Update Stack
        uses: rtsarakaki/actions-aws-deploy@main
        with:
          stack_name: ${{ env.STACK_NAME }}
          template_file: ${{ env.TEMPLATE_FILE }}
          user_password: ${{ secrets.USER_PASSWORD }}
          aws_region: ${{ vars.AWS_REGION }}
          dry_run: false
